openapi: 3.0.1
info:
  title: Piggy bank sample app
  description: 'a sample documentation for the statistics service'
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more on GitHub
  url: https://github.com/graphaware
tags:
  - name: statistics
    description: Statistics service
    externalDocs:
      description: Find out more
      url: https://github.com/graphaware
paths:
  /statistics/{accountName}:
    put:
      tags:
        - statistics
      summary: Update account stats
      operationId: saveAccountStatistics
      parameters:
        - name: accountName
          in: path
          description: Name of the account to update
          required: true
          schema:
            type: string
      requestBody:
        description: Account object that needs to be added to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
        required: true
      responses:
        400:
          description: Invalid content supplied
          content: {}
        404:
          description: Account not found
          content: {}
      security:
        - stats_auth:
            - write:accounts-stats
            - read:accounts-stats
    get:
      tags:
        - statistics
      summary: Get account stats
      description: Get stats for a specific account
      operationId: getStatisticsByAccountName
      parameters:
        - name: accountName
          in: path
          description: Name of the account to update
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DataPoint'
        400:
          description: Invalid tag value
          content: {}
      security:
        - stats_auth:
            - write:accounts-stats
            - read:accounts-stats
  /statistics/current:
    get:
      tags:
        - statistics
      summary: Finds current account stats
      description: Get statistics about the currently connected user
      operationId: getCurrentAccountStatistics
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DataPoint'
        400:
          description: Invalid status value
          content: {}
components:
  schemas:
    Account:
      type: object
      properties:
        incomes:
          type: array
          items:
            type: string
        expenses:
          type: array
          items:
            type: string
        saving:
          type: string
    DataPoint:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
  securitySchemes:
    stats_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://stats/oauth/dialog
          scopes:
            write:accounts-stats: modify stats in your account
            read:accounts-stats: read your stats
    api_key:
      type: apiKey
      name: api_key
      in: header
